services:
  - type: web
    name: taskify-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://thiagopeire123:Thrasher616@cluster.mongodb.net/
      - key: SECRET_KEY
        value: ">GsQS@riUIR!2jG)kEsCZ+;{|NTmJzTJt\"8AyWbbg$u4NPGlA%@cs@.hCsQ<"